### ISSUE TITLE
Sweep:  features

### ISSUE THREAD

**Issue by thoriqazzikraa** [The-MoonTg-project/Moon-Userbot#95]
### Details
request for global cast features

**Comment by AbhiTheModder** [comment]
> request for global cast features

@thoriqazzikraa could you please provide more details

**Comment by thoriqazzikraa** [comment]
> > request for global cast features
> 
> @thoriqazzikraa could you please provide more details

like broadcast message to the all group message
ex: `.gcast test`

**Comment by AbhiTheModder** [comment]
> > > request for global cast features
> > 
> > 
> > @thoriqazzikraa could you please provide more details
> 
> like broadcast message to the all group message ex: `.gcast test`

No, that violates telegram's ToC, MoonUB isn't going to provide it internally however if you wish to do so you can create your own custom modules to do so.

Thanks
